name: Release Documentation

permissions: write-all

on:
  pull_request:
    paths:
      - compass/**
      - docs/**
      - .github/workflows/docs.yml
      - pyproject.toml
      - pixi.lock
  push:
    branches: [main]
    paths:
      - compass/**
      - docs/**
      - .github/workflows/docs.yml
      - pyproject.toml
      - pixi.lock
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Pull Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.62.2
          locked: true
          cache: false  # Don't use cache because we use the ``pdoc`` environment
          environments: pdoc

      - name: Build Docs
        run: pixi run -e pdoc python-docs  # This errors on warnings

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
